/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mgh.edd.proyectogradleterminal.app;

import com.mgh.edd.proyectogradleterminal.list.LinkedList;
import static com.mgh.edd.proyectogradleterminal.utilities.StringUtils.join;
import static com.mgh.edd.proyectogradleterminal.utilities.StringUtils.split;
import static com.mgh.edd.proyectogradleterminal.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        int num1 = 10;
        int num2 = 5;

        System.out.println("Suma: " + Operaciones.sumar(num1, num2));
        System.out.println("Resta: " + Operaciones.restar(num1, num2));
    }
}